version: '3.8'

services:
  redis_realtorbuddycore:
    container_name: redis_realtorbuddycore
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  db_realtorbuddycore:
    container_name: db_realtorbuddycore
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_realtorbuddycore
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./db-init:/docker-entrypoint-initdb.d
    restart: always

  api-realtorbuddycore:
    container_name: api-realtorbuddycore
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: >
      sh -c 
          "python manage.py makemigrations &&
          python manage.py migrate &&
          python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - PORT=8000
    restart: unless-stopped
    depends_on:
      - db_realtorbuddycore

  worker-realtorbuddycore:
    container_name: worker-realtorbuddycore
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A APIRealtorBuddyCore worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DEBUG=1
    restart: unless-stopped
    depends_on:
      - api-realtorbuddycore
      - db_realtorbuddycore
      - redis_realtorbuddycore

  beat-realtorbuddycore:
    container_name: beat-realtorbuddycore
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A APIRealtorBuddyCore beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    environment:
      - DEBUG=1
    restart: unless-stopped
    depends_on:
      - api-realtorbuddycore
      - db_realtorbuddycore
      - redis_realtorbuddycore

volumes:
  pgdata: