# Generated by Django 3.2.24 on 2024-03-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField()),
                ('num_segments', models.CharField(max_length=10)),
                ('direction', models.CharField(max_length=20)),
                ('from_number', models.CharField(db_index=True, max_length=30)),
                ('to_number', models.CharField(db_index=True, max_length=30)),
                ('date_updated', models.DateTimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uri', models.URLField()),
                ('account_sid', models.CharField(max_length=50)),
                ('num_media', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('messaging_service_sid', models.CharField(blank=True, max_length=50, null=True)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('price_unit', models.CharField(max_length=10)),
                ('api_version', models.CharField(max_length=20)),
                ('subresource_uris', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
