# Generated by Django 3.2.24 on 2024-04-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('to_country', models.CharField(blank=True, max_length=10, null=True)),
                ('to_state', models.CharField(blank=True, max_length=10, null=True)),
                ('sms_message_sid', models.CharField(blank=True, max_length=34, null=True, unique=True)),
                ('num_media', models.CharField(blank=True, max_length=3, null=True)),
                ('to_city', models.CharField(blank=True, max_length=50, null=True)),
                ('from_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('sms_sid', models.CharField(blank=True, max_length=34, null=True)),
                ('from_state', models.CharField(blank=True, max_length=10, null=True)),
                ('sms_status', models.CharField(blank=True, max_length=20, null=True)),
                ('from_city', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('from_country', models.CharField(blank=True, max_length=10, null=True)),
                ('to_number', models.CharField(max_length=30)),
                ('to_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('num_segments', models.CharField(blank=True, max_length=3, null=True)),
                ('message_sid', models.CharField(blank=True, max_length=34, null=True)),
                ('account_sid', models.CharField(blank=True, max_length=34, null=True)),
                ('from_number', models.CharField(max_length=30)),
                ('api_version', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sms_message_sid', models.CharField(blank=True, max_length=34, null=True, unique=True)),
                ('sms_sid', models.CharField(blank=True, max_length=34, null=True)),
                ('wa_id', models.CharField(blank=True, max_length=20, null=True)),
                ('num_media', models.CharField(blank=True, max_length=3, null=True)),
                ('profile_name', models.CharField(blank=True, max_length=100, null=True)),
                ('message_type', models.CharField(blank=True, max_length=10, null=True)),
                ('sms_status', models.CharField(blank=True, max_length=20, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('to_number', models.CharField(max_length=30)),
                ('from_number', models.CharField(max_length=30)),
                ('num_segments', models.CharField(blank=True, max_length=3, null=True)),
                ('referral_num_media', models.CharField(blank=True, max_length=3, null=True)),
                ('message_sid', models.CharField(blank=True, max_length=34, null=True)),
                ('account_sid', models.CharField(blank=True, max_length=34, null=True)),
                ('api_version', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
