# Generated by Django 3.2.24 on 2024-05-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twilioService', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatsAppMessage',
        ),
    ]
