# Generated by Django 4.2.13 on 2024-06-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilioService', '0002_delete_whatsappmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textmessage',
            name='sms_message_sid',
        ),
        migrations.RemoveField(
            model_name='textmessage',
            name='sms_sid',
        ),
        migrations.AddField(
            model_name='textmessage',
            name='fub_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textmessage',
            name='message_service_sid',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='message_sid',
            field=models.CharField(blank=True, max_length=34, null=True, unique=True),
        ),
    ]
