# Generated by Django 3.2.24 on 2024-03-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilioService', '0003_whatsappmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='sms_message_sid',
            field=models.CharField(blank=True, max_length=34, null=True, unique=True),
        ),
    ]
