# Generated by Django 4.2.13 on 2024-06-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twilioService', '0003_remove_textmessage_sms_message_sid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textmessage',
            name='fub_message_id',
        ),
    ]
