# Generated by Django 3.2.24 on 2024-03-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilioService', '0004_alter_whatsappmessage_sms_message_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='account_sid',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message_sid',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='num_media',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='sms_sid',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='wa_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
