# Generated by Django 3.2.24 on 2024-03-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilioService', '0005_auto_20240325_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='api_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='num_segments',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='sms_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
