# Generated by Django 3.2.24 on 2024-03-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilioService', '0006_auto_20240325_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
