# Generated by Django 4.2.13 on 2024-06-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('contacted', models.BooleanField(default=False)),
                ('replied', models.BooleanField(default=False)),
                ('contacted_date', models.DateField(blank=True, null=True)),
                ('last_contacted', models.DateField(blank=True, null=True)),
                ('contacted_times', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='clientEmailDefinition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('key', models.IntegerField()),
                ('days', models.IntegerField()),
                ('weekends', models.BooleanField()),
                ('days_wait', models.IntegerField()),
                ('email_subject', models.CharField(max_length=100)),
                ('email_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='clientEmailOutReachRuleset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('new_clients_daily', models.IntegerField()),
                ('follow_up_clients_daily', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='emailStage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientOutreachService.client')),
            ],
        ),
        migrations.CreateModel(
            name='emailStageDefinition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='emailStageHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientOutreachService.client')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientOutreachService.emailstage')),
            ],
        ),
        migrations.AddField(
            model_name='emailstage',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientOutreachService.emailstagedefinition'),
        ),
    ]
