# Generated by Django 4.2.13 on 2024-07-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientOutreachService', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientemaildefinition',
            name='days',
        ),
        migrations.AlterField(
            model_name='client',
            name='contacted_times',
            field=models.IntegerField(default=0),
        ),
    ]
