# Generated by Django 4.2.13 on 2024-07-08 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientOutreachService', '0002_remove_clientemaildefinition_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientEmailLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientOutreachService.client')),
                ('email_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientOutreachService.clientemaildefinition')),
            ],
        ),
        migrations.RemoveField(
            model_name='emailstagehistory',
            name='client',
        ),
        migrations.RemoveField(
            model_name='emailstagehistory',
            name='stage',
        ),
        migrations.DeleteModel(
            name='emailStage',
        ),
        migrations.DeleteModel(
            name='emailStageDefinition',
        ),
        migrations.DeleteModel(
            name='emailStageHistory',
        ),
    ]
