# Generated by Django 4.2.13 on 2024-07-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientOutreachService', '0004_remove_client_city_remove_client_contacted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(),
        ),
    ]
