# Generated by Django 4.2.13 on 2024-07-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientOutreachService', '0005_alter_client_email_alter_client_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientemaillogs',
            old_name='email_type',
            new_name='email',
        ),
    ]
