# Generated by Django 3.2.24 on 2024-05-28 10:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressAbbreviation',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('standard_abbreviation', models.CharField(max_length=10, unique=True)),
                ('common_forms', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('address_normalized', models.TextField(editable=False)),
                ('neighborhood', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('phone_normalized', models.TextField(blank=True, editable=False, null=True)),
                ('website', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperate', models.BooleanField(blank=True, default=False, null=True)),
                ('cooperation_fixed', models.IntegerField(blank=True, null=True)),
                ('cooperation_percentage', models.IntegerField(blank=True, null=True)),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cooperation', to='buildingService.building')),
            ],
        ),
        migrations.CreateModel(
            name='CooperationHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('cooperate', models.BooleanField(default=False)),
                ('cooperation_fixed', models.IntegerField(blank=True, null=True)),
                ('cooperation_percentage', models.IntegerField(blank=True, null=True)),
                ('cooperation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='buildingService.cooperation')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
