# Generated by Django 3.2.24 on 2024-04-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='phone_normalized',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
