# Generated by Django 3.2.24 on 2024-04-02 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildingService', '0002_auto_20240321_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperation',
            name='cooperation_type',
        ),
        migrations.AddField(
            model_name='cooperation',
            name='fixed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperations', to='buildingService.building'),
        ),
    ]
