# Generated by Django 3.2.24 on 2024-04-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildingService', '0002_building_phone_normalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperation', to='buildingService.building'),
        ),
    ]
