# Generated by Django 3.2.24 on 2024-04-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingService', '0003_alter_cooperation_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
