# Generated by Django 3.2.24 on 2024-04-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingService', '0003_auto_20240402_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='company',
        ),
        migrations.RemoveField(
            model_name='building',
            name='min_lease_term',
        ),
        migrations.RemoveField(
            model_name='building',
            name='n_floors',
        ),
        migrations.RemoveField(
            model_name='building',
            name='n_units',
        ),
        migrations.RemoveField(
            model_name='building',
            name='year_built',
        ),
        migrations.RemoveField(
            model_name='building',
            name='year_renovated',
        ),
        migrations.AddField(
            model_name='cooperation',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='cooperate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
