# Generated by Django 3.2.24 on 2024-04-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingService', '0004_alter_building_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='uuid',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
