# Generated by Django 3.2.24 on 2024-04-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingService', '0004_auto_20240403_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
