# Generated by Django 3.2.24 on 2024-05-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingService', '0005_alter_building_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
