# Generated by Django 3.2.24 on 2024-05-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildingService', '0006_cooperation_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperation',
            name='title',
        ),
        migrations.CreateModel(
            name='CooperationHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('cooperate', models.BooleanField(default=False)),
                ('cooperation_fixed', models.IntegerField(blank=True, null=True)),
                ('cooperation_percentage', models.IntegerField(blank=True, null=True)),
                ('cooperation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='buildingService.cooperation')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
