# Generated by Django 3.2.24 on 2024-05-25 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildingService', '0007_auto_20240525_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='building',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cooperation', to='buildingService.building'),
        ),
    ]
